---

- hosts: all
  become: true
  tasks: 

  - name: install updates (CentOS)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: copy defualt html file for site
    tags: apache
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root 
      group: roog
      mode: 0644

  - name: install apache and php for Ubuntu servers
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php CentOS servers
    dnf: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" 

- hosts: all
  become: true
  tasks: 

  - name: install mariadb pacage (CentOS)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package "Ubuntu"
    apt: 
      name: mariadb
      state: latest
    when: ansible_distribution -- "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest

