---

- hosts: all
  become: true
  become_method: sudo
   include_vars:
      - centos.yml
      - ubuntu.yml
  tasks: 

  - name: add php support for apache
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_pacage }}"
      state: present
      update_cache: yes

 
  - name: start httpd service
    service: 
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: open firewalld for httpd
    firewalld: 
      service: https
      state: enabled
      permanent: yes
    when: ansible_distribution == "CentOS"


